title: 0xfarism
email: ""
description: Offensive security, systems security, and detection engineering notes.
url: "https://fmujcinagic.github.io"
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM
collections:
  articles:
    output: true
    permalink: /posts/:name/
exclude:
  - README.md
